#!/usr/bin/env bash
# TTFX baseline harness — the lean "First-Run Study" for Julia cold-start cost.
#
# For each target package, measured in SEPARATE processes (JIT state is
# per-process; a warm rerun inside one process would measure nothing):
#   1. precompile  — wall time of Pkg.precompile after purging the package's
#                    compiled cache (true cold mobilization)
#   2. load        — `using Pkg` time in a fresh process, pkgimage already cached
#   3. ttfx        — first representative call in that same fresh process
#   4. invalidations — unique methods invalidated by loading the package
#
# Output: bench/results/baseline-<date>.csv — one tidy header + one row per
# package (rectangular; no ragged rows), plus a Markdown table alongside it.
#
# Usage: bash bench/run.sh
set -euo pipefail

cd "$(dirname "$0")/.."
PACKAGES=(CSV DataFrames Plots)
STAMP=$(date +%F)
CSV_OUT="bench/results/baseline-$STAMP.csv"
MD_OUT="bench/results/baseline-$STAMP.md"
mkdir -p bench/results

JV=$(julia --startup-file=no -e 'print(VERSION)')
echo "julia_version,package,precompile_s,load_s,ttfx_s,invalidated_methods,invalidation_trees" > "$CSV_OUT"

{
  echo "# TTFX Baseline — $STAMP"
  echo
  echo "Julia $JV · one fresh process per measurement · generated by \`bench/run.sh\`"
  echo
  echo "| Package | Cold precompile (s) | Load \`using\` (s) | TTFX first call (s) | Invalidated methods | Invalidation trees |"
  echo "|---|---:|---:|---:|---:|---:|"
} > "$MD_OUT"

for pkg in "${PACKAGES[@]}"; do
  echo "=== $pkg ===" >&2

  # 1. cold precompile: purge this package's compiled cache, then re-precompile
  pre=$(julia --startup-file=no --project=bench -e "
    using Pkg
    for dir in Base.DEPOT_PATH
        cache = joinpath(dir, \"compiled\", \"v\$(VERSION.major).\$(VERSION.minor)\", \"$pkg\")
        isdir(cache) && rm(cache; recursive=true)
    end
    t = @elapsed Pkg.precompile(\"$pkg\")
    println(\"PRECOMPILE_RESULT,$pkg,\", round(t; digits=3))
  " | grep '^PRECOMPILE_RESULT' | cut -d, -f3)

  # 2+3. load + TTFX in one fresh process
  ttfx_line=$(julia --startup-file=no --project=bench bench/ttfx.jl "$pkg" | grep '^TTFX_RESULT')
  load=$(printf '%.3f' "$(echo "$ttfx_line" | cut -d, -f3)")
  ttfx=$(printf '%.3f' "$(echo "$ttfx_line" | cut -d, -f4)")

  # 4. invalidation count in another fresh process
  inv_line=$(julia --startup-file=no --project=bench bench/invalidations.jl "$pkg" | grep '^INVALIDATIONS_RESULT')
  n_inv=$(echo "$inv_line" | cut -d, -f3)
  n_trees=$(echo "$inv_line" | cut -d, -f4)

  echo "$JV,$pkg,$pre,$load,$ttfx,$n_inv,$n_trees" >> "$CSV_OUT"
  echo "| $pkg | $pre | $load | $ttfx | $n_inv | $n_trees |" >> "$MD_OUT"
  echo "$pkg: precompile=${pre}s load=${load}s ttfx=${ttfx}s invalidated=$n_inv trees=$n_trees" >&2
done

echo "Results written to $CSV_OUT and $MD_OUT" >&2
